### 🔹 Why File I/O Matters (Big Picture First)

Normally, when you run a Python program, everything disappears when it ends.

It’s like writing something on a whiteboard and wiping it immediately.

File I/O fixes that.

Now your program can:

Save data → like saving contacts to your phone
Load data → like opening WhatsApp and seeing old chats
Share data → like exporting a report

💡 Real-life example:
A banking app saves your balance in a file (or database). If it didn’t, your money would reset every time you open the app 😅

----
#### 🔹 Section 1: Reading Text Files
##### 1.1 Basic File Reading

This is simply:
👉 “Open a file and read everything inside it”

💡 Example:
You open a notebook and read everything written in it.

In [ ]:
file = open('traaqa.txt', 'r')
content = file.read()
print(content)
file.close()

Main Features & Structure

1. Budgets:
   Displays all user-created budgets.
   Users can create new budgets, define time frames, and allocate amounts across categories.
   Selecting a budget opens a detailed view showing its category structure and spending progress.

2. Categories:
   Displays the hierarchical structure of categories within a selected budget.
   Users can create, edit, and nest categories at multiple levels.
   Parent category values are automatically calculated as the sum of their child categories.

3. Expenses:
   Allows users to log and view all spending records.
   Each expense includes amount, category, date, and optional notes.
   Expenses are automatically mapped to budget categories and tracked against planned amounts.

4. Analytics:
   Provides insights into total spending, category breakdowns, and trends over time.
   Highlights differences between planned and actual spending.
   Presents information in a clear, simple, and human-readable format.

5. AI Insights:
   Analyzes user spending behavior to detect unusual patterns.
   Suggests areas where users can reduce spending.
   Recommends adjustments to improve future budgets.
   Communicates insights in a conversational and easy-to-understand manner.

6. User Experience & Interface:
   The app follows a minimal, modern, and intuitive design.
   Prioritizes fast expense logging and clear visibility of budget status.
   Avoids complex workflows and unnecessary steps.

7. Data Export:
   Users can export their data at any time in CSV format.
   Export includes both budget structures and expense records for external use.

`'r'` means read mode
`read()` means read everything

⚠️ Important:
You must __close__ the file, like closing a book after reading.




🔹 So why must you close it?
1. To free up system resources
2. To make sure your data is actually saved

In [27]:
# readline() — reads one line at a time
file = open('traaqa.txt', 'r')
line1 = file.readline()
line2 = file.readline()
print(f"Line 1: {line1}")
print(f"Line 2: {line2}")
file.close()

Line 1: Main Features & Structure

Line 2:

##### 1.2 Reading Line by Line

In [28]:
file = open('traaqa.txt', 'r')
print(file.readline())
print(file.readline())
file.close()

Main Features & Structure

##### 1.3 Iterating Through Lines

In [29]:
# readlines() — reads all lines into a list
file = open('traaqa.txt', 'r')
lines = file.readlines()
for line in lines:
    print(line.strip())  # strip() removes \n
file.close()

Main Features & Structure

1. Budgets:
Displays all user-created budgets.
Users can create new budgets, define time frames, and allocate amounts across categories.
Selecting a budget opens a detailed view showing its category structure and spending progress.

2. Categories:
Displays the hierarchical structure of categories within a selected budget.
Users can create, edit, and nest categories at multiple levels.
Parent category values are automatically calculated as the sum of their child categories.

3. Expenses:
Allows users to log and view all spending records.
Each expense includes amount, category, date, and optional notes.
Expenses are automatically mapped to budget categories and tracked against planned amounts.

4. Analytics:
Provides insights into total spending, category breakdowns, and trends over time.
Highlights differences between planned and actual spending.
Presents information in a clear, simple, and human-readable format.

5. AI Insights:
Analyzes user spending behavior to detect unusual patterns.
Suggests areas where users can reduce spending.
Recommends adjustments to improve future budgets.
Communicates insights in a conversational and easy-to-understand manner.

6. User Experience & Interface:
The app follows a minimal, modern, and intuitive design.
Prioritizes fast expense logging and clear visibility of budget status.
Avoids complex workflows and unnecessary steps.

7. Data Export:
Users can export their data at any time in CSV format.
Export includes both budget structures and expense records for external use.

In [30]:
with open('traaqa.txt', 'r') as traaqa:
    for line in  traaqa.readlines():
        print(line)

Main Features & Structure



1. Budgets:

   Displays all user-created budgets.

   Users can create new budgets, define time frames, and allocate amounts across categories.

   Selecting a budget opens a detailed view showing its category structure and spending progress.



2. Categories:

   Displays the hierarchical structure of categories within a selected budget.

   Users can create, edit, and nest categories at multiple levels.

   Parent category values are automatically calculated as the sum of their child categories.



3. Expenses:

   Allows users to log and view all spending records.

   Each expense includes amount, category, date, and optional notes.

   Expenses are automatically mapped to budget categories and tracked against planned amounts.



4. Analytics:

   Provides insights into total spending, category breakdowns, and trends over time.

   Highlights differences between planned and actual spending.

   Presents information in a clear, simple, and human-readable format.



5. AI Insights:

   Analyzes user spending behavior to detect unusual patterns.

   Suggests areas where users can reduce spending.

   Recommends adjustments to improve future budgets.

   Communicates insights in a conversational and easy-to-understand manner.



6. User Experience & Interface:

   The app follows a minimal, modern, and intuitive design.

   Prioritizes fast expense logging and clear visibility of budget status.

   Avoids complex workflows and unnecessary steps.



7. Data Export:

   Users can export their data at any time in CSV format.

   Export includes both budget structures and expense records for external use.

-----
#### 🔹 Section 2: Writing Text Files

##### 2.1 Basic Writing
`open('output.txt', 'w')`

👉 `'w'` means:

- Create a new file OR
- Delete everything inside and start fresh

💡 Real-life:
Like opening a notebook and tearing out all pages before writing again 😬

In [32]:
# Write to a file (overwrites if exists)
file = open('output.txt', 'w')
file.write('Hello, File!\n')
file.write('This is a new line.\n')
file.close()


file = open('output.txt', 'r')
print(file.read())
file.close()

Hello, File!
This is a new line.

In [31]:
with open('write_test.txt', 'a') as filex:
    filex.write('\nIt is our dream that many people will enjoy using our app.')

with open('write_test.txt', 'r') as filex:
    for line in filex.readlines():
        print(line)

It is our dream that many people will enjoy using our app.

##### 2.2 Appending

In [33]:
with open('traaqa.txt', 'a') as filex:
    filex.write('\n We hope you enjoy using our app.')

with open('traaqa.txt', 'r') as filey:
    content = filey.read()
    print(content)

Main Features & Structure

1. Budgets:
   Displays all user-created budgets.
   Users can create new budgets, define time frames, and allocate amounts across categories.
   Selecting a budget opens a detailed view showing its category structure and spending progress.

2. Categories:
   Displays the hierarchical structure of categories within a selected budget.
   Users can create, edit, and nest categories at multiple levels.
   Parent category values are automatically calculated as the sum of their child categories.

3. Expenses:
   Allows users to log and view all spending records.
   Each expense includes amount, category, date, and optional notes.
   Expenses are automatically mapped to budget categories and tracked against planned amounts.

4. Analytics:
   Provides insights into total spending, category breakdowns, and trends over time.
   Highlights differences between planned and actual spending.
   Presents information in a clear, simple, and human-readable format.

5. AI Insights:
   Analyzes user spending behavior to detect unusual patterns.
   Suggests areas where users can reduce spending.
   Recommends adjustments to improve future budgets.
   Communicates insights in a conversational and easy-to-understand manner.

6. User Experience & Interface:
   The app follows a minimal, modern, and intuitive design.
   Prioritizes fast expense logging and clear visibility of budget status.
   Avoids complex workflows and unnecessary steps.

7. Data Export:
   Users can export their data at any time in CSV format.
   Export includes both budget structures and expense records for external use.
 We hope you enjoy using our app.

-----
### 🔹 Section 3: File Modes

These are just different ways to open a file.

Think of it like opening a door:


| Mode | Description |
|------|-------------|
| `'r'` | Read (default). File must exist: *Just look (read only)* |
| `'w'` | Write. Creates file or overwrites: *Start fresh (erase + write)* |
| `'a'` | Append. Creates file or adds to end: *Add more*|
| `'r+'` | Read and write. File must exist: *Read + edit*|
| `'w+'` | Read and write. Creates or overwrites: *Reset + read + write*|
| `'rb'` | Read binary. |
| `'wb'` | Write binary. |

----
### Section 4: The with Statement
`with` is a way of saying:

_“Use this resource for a short time, and clean it up automatically when you're done.”_

That “resource” can be:

- a file
- a network connection
- a database
- etc.


#### 🔹 Compare the two approaches
##### ❌ Without with
- `file = open("data.txt", "r")`
- `content = file.read()`
- `file.close()`

*This works… but only if everything goes perfectly.*

🔹 The hidden problem

What if something goes wrong?

- `file = open("data.txt", "r")`
- `content = file.read()`

- `# 💥 error happens here`
- `print(10 / 0)`

- `file.close()`  # ❌ this never runs

👉 The file is left open

##### ✅ With with
- `with open("data.txt", "r") as file:`
-     `content = file.read()`

##### Even if an error happens inside:

👉 Python automatically closes the file for you

----
### 🔹 Section 5: File Paths

*This is about where your file is located.*

#### 5.1 Absolute vs Relative Paths
##### Absolute Path

👉 Full location

- Windows: `C:\Users\Alice\Documents\file.txt`
- Mac/Linux: `/home/alice/documents/file.txt`

_House 10, Street 5, Abuja, Nigeria_


##### Relative Path

👉 Based on where you are

- `data.txt` — same folder
- `data/file.txt` — in `data` subfolder
- `../file.txt` — parent folder

## Section 5.2 — Building File Paths That Work on Any Computer

Imagine you're giving someone directions to your house. If you live in Lagos and you tell them *"turn left at the big mango tree"*, those directions only make sense locally — someone in Abuja has no idea what mango tree you're talking about. File paths have the same problem.

Windows computers use backslashes to separate folders: `data\files\output.txt`. Mac and Linux use forward slashes: `data/files/output.txt`. If you type a path manually in your code, it works on your computer and breaks on someone else's.

---

### The Problem — A File Buried 5 Folders Deep

Imagine you're building a school management system and a student report is stored here:

```
school → academics → year2 → term1 → reports → student_report.txt
```

A beginner might type the path directly:

```python
# Works on Mac/Linux, breaks on Windows
path = 'school/academics/year2/term1/reports/student_report.txt'

# Works on Windows, breaks on Mac/Linux
path = 'school\\academics\\year2\\term1\\reports\\student_report.txt'
```

Both are fragile. You'd have to rewrite the path every time you shared your code with someone on a different computer.

---

### The Solution — `os.path.join()`

Instead of typing the slash yourself, you hand Python the folder names as separate pieces and let it figure out the correct separator for whatever computer the code is running on:

```python
import os

path = os.path.join('school', 'academics', 'year2', 'term1', 'reports', 'student_report.txt')

print(path)
# On Mac/Linux →  school/academics/year2/term1/reports/student_report.txt
# On Windows   →  school\academics\year2\term1\reports\student_report.txt

# Use it to open the file
with open(path, 'r') as f:
    print(f.read())
```

Think of `os.path.join()` like a GPS app. You don't tell the GPS *"turn left, then right"* — you just give it the destination pieces and it figures out the correct route for your current location. You just give Python the folder names and it builds the correct path for whichever operating system is running.

---

### Why is this better? Three reasons

**1. It works everywhere, automatically.**
Write the code once. Your classmate on Windows, your lecturer on a Mac, and a server running Linux will all get the correct path without anyone changing a single character.

**2. It's easier to read and modify.**
Each folder name is clearly separated by a comma. If you need to add or remove a folder, you just add or remove one item — no hunting for slashes inside a long string.

**3. It handles edge cases for you.**
If a folder name accidentally has a trailing slash, `os.path.join()` is smart enough not to double it up. If you built the path manually, you'd have to check for that yourself.

---

### Bonus Tool — `os.path.abspath()`

A relative path like `'student_report.txt'` is a shortcut — it only makes sense if you know which folder Python is currently running from. `abspath()` converts that shortcut into the full, unambiguous address:

```python
abs_path = os.path.abspath('student_report.txt')
print(abs_path)
# Mac/Linux →  /home/alice/school/academics/year2/term1/reports/student_report.txt
# Windows   →  C:\Users\Alice\school\academics\year2\term1\reports\student_report.txt
```

This is like the difference between *"I live two streets down"* (only useful if you know where the conversation is happening) versus *"14 Adeola Street, Victoria Island, Lagos"* — unambiguous from anywhere in the world.

---

> **The golden rule:** never type slashes in your paths manually. Always use `os.path.join()` to build paths, and your code will run correctly on any computer without modification.

In [39]:
path1 = r"C:\Users\Emigb\Documents\Data\Data Science\datasets\austin_weather.csv"
print(path1)

import pandas as pd
file1 = pd.read_csv(path1)
file1.head()

C:\Users\Emigb\Documents\Data\Data Science\datasets\austin_weather.csv

,STATION,NAME,DATE,MLY-CLDD-BASE45,MLY-CLDD-BASE50,MLY-CLDD-BASE55,MLY-CLDD-BASE57,MLY-CLDD-BASE60,MLY-CLDD-BASE70,MLY-CLDD-BASE72,...,MLY-TMIN-AVGNDS-LSTH060,MLY-TMIN-AVGNDS-LSTH070,MLY-TMIN-NORMAL,MLY-TMIN-PRBOCC-LSTH016,MLY-TMIN-PRBOCC-LSTH020,MLY-TMIN-PRBOCC-LSTH024,MLY-TMIN-PRBOCC-LSTH028,MLY-TMIN-PRBOCC-LSTH032,MLY-TMIN-PRBOCC-LSTH036,MLY-TMIN-STDDEV
0,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",1,190,103,50,35,18,1,-7777,...,302,310,36.3,298,570,839,967,997,1000,2.9
1,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",2,228,132,68,49,29,3,1,...,264,280,39.4,103,327,614,867,973,999,3.2
2,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",3,446,306,185,146,98,13,6,...,270,308,46.6,10,73,242,494,761,928,3.6
3,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",4,668,519,373,318,240,53,32,...,193,287,54.7,0,0,0,48,189,453,4.1
4,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",5,936,781,626,564,471,181,134,...,89,250,63.7,0,0,0,0,0,0,2.5

In [49]:
import os
path2 = os.path.join('C:\\','Users','Emigb','Documents','Data','Data Science','datasets','austin_weather.csv')
print(path2)

import pandas as pd
file1 = pd.read_csv(path1)
file1.head()

C:\Users\Emigb\Documents\Data\Data Science\datasets\austin_weather.csv

,STATION,NAME,DATE,MLY-CLDD-BASE45,MLY-CLDD-BASE50,MLY-CLDD-BASE55,MLY-CLDD-BASE57,MLY-CLDD-BASE60,MLY-CLDD-BASE70,MLY-CLDD-BASE72,...,MLY-TMIN-AVGNDS-LSTH060,MLY-TMIN-AVGNDS-LSTH070,MLY-TMIN-NORMAL,MLY-TMIN-PRBOCC-LSTH016,MLY-TMIN-PRBOCC-LSTH020,MLY-TMIN-PRBOCC-LSTH024,MLY-TMIN-PRBOCC-LSTH028,MLY-TMIN-PRBOCC-LSTH032,MLY-TMIN-PRBOCC-LSTH036,MLY-TMIN-STDDEV
0,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",1,190,103,50,35,18,1,-7777,...,302,310,36.3,298,570,839,967,997,1000,2.9
1,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",2,228,132,68,49,29,3,1,...,264,280,39.4,103,327,614,867,973,999,3.2
2,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",3,446,306,185,146,98,13,6,...,270,308,46.6,10,73,242,494,761,928,3.6
3,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",4,668,519,373,318,240,53,32,...,193,287,54.7,0,0,0,48,189,453,4.1
4,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",5,936,781,626,564,471,181,134,...,89,250,63.7,0,0,0,0,0,0,2.5

In [50]:
import os


base_dir = r'C:\Users\Emigb\Documents\Data\Data Science'
file_dir = r'datasets\austin_weather.csv'

path2 = os.path.join(base_dir, file_dir)
print(path2)

import pandas as pd
file2 = pd.read_csv(path2)
file2.head()

C:\Users\Emigb\Documents\Data\Data Science\datasets\austin_weather.csv

,STATION,NAME,DATE,MLY-CLDD-BASE45,MLY-CLDD-BASE50,MLY-CLDD-BASE55,MLY-CLDD-BASE57,MLY-CLDD-BASE60,MLY-CLDD-BASE70,MLY-CLDD-BASE72,...,MLY-TMIN-AVGNDS-LSTH060,MLY-TMIN-AVGNDS-LSTH070,MLY-TMIN-NORMAL,MLY-TMIN-PRBOCC-LSTH016,MLY-TMIN-PRBOCC-LSTH020,MLY-TMIN-PRBOCC-LSTH024,MLY-TMIN-PRBOCC-LSTH028,MLY-TMIN-PRBOCC-LSTH032,MLY-TMIN-PRBOCC-LSTH036,MLY-TMIN-STDDEV
0,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",1,190,103,50,35,18,1,-7777,...,302,310,36.3,298,570,839,967,997,1000,2.9
1,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",2,228,132,68,49,29,3,1,...,264,280,39.4,103,327,614,867,973,999,3.2
2,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",3,446,306,185,146,98,13,6,...,270,308,46.6,10,73,242,494,761,928,3.6
3,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",4,668,519,373,318,240,53,32,...,193,287,54.7,0,0,0,48,189,453,4.1
4,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",5,936,781,626,564,471,181,134,...,89,250,63.7,0,0,0,0,0,0,2.5

### 🔹 Section 6: Working with CSV Files

### What is a CSV file?

A **CSV (Comma-Separated Values)** file is a simple spreadsheet stored as plain text. Each row is a line, and each column is separated by a comma. Think of it as an Excel spreadsheet you can open in Notepad.

Example of what a CSV looks like inside:
```
Name,Age,City
Alice,28,NYC
Bob,32,LA
```

In [4]:
import csv

with open('students.csv', 'r') as students:
    reader = csv.reader(students)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['Alice', '28', 'NYC']
['Bob', '32', 'LA']
['Charlie', '25', 'Chicago']
['Diana', '29', 'Houston']
['Eve', '35', 'Phoenix']

##### 6.2 Reading CSV as Dictionaries

In [7]:
with open('students.csv', 'r') as stdnt:
    for row in csv.DictReader(stdnt):
        print(row)

{'Name': 'Alice', 'Age': '28', 'City': 'NYC'}
{'Name': 'Bob', 'Age': '32', 'City': 'LA'}
{'Name': 'Charlie', 'Age': '25', 'City': 'Chicago'}
{'Name': 'Diana', 'Age': '29', 'City': 'Houston'}
{'Name': 'Eve', 'Age': '35', 'City': 'Phoenix'}

##### Why would you want to read your csv files as dictionaries?

Great question! It's all about **convenience when accessing specific values.**

When you read as a plain list, each row comes back like this:

```python
['Alice', '28', 'NYC']
```

To get Alice's city, you'd have to write `row[2]` — you have to **remember that index 2 means City**. That's fine for 3 columns, but imagine a spreadsheet with 20 columns. Remembering that index 14 means "postal code" becomes a nightmare.

When you read as a dictionary, the same row comes back like this:

```python
{'Name': 'Alice', 'Age': '28', 'City': 'NYC'}
```

Now you just write `row['City']` — **no memorizing positions**, the column name tells you exactly what you're getting.

---

A real-life comparison: imagine you ordered a package and it arrives in a plain unlabelled box with items just thrown inside. That's the list — you have to dig around and count positions to find what you want. The dictionary version is the same box but every item has a sticky label on it. Much easier to find what you need.

---

It becomes especially useful when your code needs to do something specific, like:

```python
# Only print people who are older than 30
for row in reader:
    if int(row['Age']) > 30:
        print(row['Name'])
```

Try doing that clearly with index numbers — `row[1]` and `row[0]` — and your code becomes much harder to read and understand at a glance.

In [6]:
with open('students.csv', 'r') as stdnt:
    for row in csv.DictReader(stdnt):
        print(f"{row['Name']} is {row['Age']} years old")

Alice is 28 years old
Bob is 32 years old
Charlie is 25 years old
Diana is 29 years old
Eve is 35 years old

#### 6.3 Writing CSV Files
You can write multiple rows at once with `writerows()` (notice the **s**):

In [11]:
with open('data.csv', 'w') as file1:
    writer = csv.writer(file1)
    writer.writerow(['Name', 'Age', 'City'])  #This row will bw the header
    writer.writerow(['Alex', 31, 'Lag'])
    writer.writerow(['Barb', 26, 'PH'])
    writer.writerow(['Chazz', 23, 'ABJ'])

Alternatively you can `write` the csv file via a list

In [17]:
data = [
    ['Name', 'Age', 'City'],
    ['Jane', 32, 'Abj'],
    ['Wale', 30, 'Lag'],
    ['Jummy', 25, 'PH']
]


with open('members.csv', 'w', newline='') as filey:
    writerx =  csv.writer(filey)
    writerx.writerows(data)


with open('members.csv', 'r') as readex:
    readey = csv.reader(readex)
    for row in readey:
        print(row)

['Name', 'Age', 'City']
['Jane', '32', 'Abj']
['Wale', '30', 'Lag']
['Jummy', '25', 'PH']

In [19]:
with open('members.csv', 'r') as readex:
    readey = csv.DictReader(readex)
    for row in readey:
        print(f"My name is {row['Name']}, I'm {row['Age']} years old, and I reside in {row['City']} city.\nI am excited to meet you!")

My name is Jane, I'm 32 years old, and I reside in Abj city.
I am excited to meet you!
My name is Wale, I'm 30 years old, and I reside in Lag city.
I am excited to meet you!
My name is Jummy, I'm 25 years old, and I reside in PH city.
I am excited to meet you!

#### Section 7: Working with JSON Files
##### 7.1 What Is JSON?
**JSON (JavaScript Object Notation)** is a way to store structured, labeled data as text — like a very organized checklist or a form with named fields. It's the most popular format for saving structured data and sharing data between apps. In simple terms, it is a text format for storing structured data.

- Think of JSON as a *labeled storage box:* each compartment has a name (like "name", "age") and a value stored inside it. It's human-readable AND machine-readable.
- *Why JSON?* Unlike CSV, JSON can store nested or complex data (lists inside dictionaries, etc.), making it perfect for app settings, API responses, and configuration files.
- Human-readable
- Language-independent
- Widely used for APIs and config files

##### 7.2 Writing & Reading JSON

In [22]:
import json


data = {
    'name':'Alice',
    'age':28,
    'city':'NYC',
    'hobbies':['reading', 'hiking']
}


with open('person.json', 'w') as fileq:
    json.dump(data, fileq, indent=2)


with open('person.json', 'r') as fileq1:
    data1 = json.load(fileq1)

print(data1)
print(f"Name: {data1['name']}")       # Alice
print(f"Hobbies: {data1['hobbies']}") # ['reading', 'hiking']

{'name': 'Alice', 'age': 28, 'city': 'NYC', 'hobbies': ['reading', 'hiking']}
Name: Alice
Hobbies: ['reading', 'hiking']

##### 7.4 Working with Lists of Objects
You can also store multiple records (like a list of people) in a single JSON file:

In [26]:
pipo = [
    {'name': 'Alice','age':28},
    {'name':'Bob','age':32},
    {'name':'Chazz','age':25}
]



with open('pipo.json', 'w') as x:
    json.dump(pipo, x, indent=2)


with open('pipo.json', 'r') as y:
    loaded = json.load(y)  


for person in loaded:
    print(f"{person['name']} is {person['age']} years old")

Alice is 28 years old
Bob is 32 years old
Chazz is 25 years old